### ISSUE TITLE
Trio the example, spring XML, java config, boot

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave-webmvc-example#14]
We have questions by folks on various environments. Making a module for spring 3+ XML+servlet 2.5, spring 4 + servlet3, and finally spring boot should cover most of the bases.

**Comment by adriancole** [comment]
had a request from @jorgheymans for a spring boot example

**Comment by jorgheymans** [comment]
thanks for this, would be helpful. In addition to this, the relation between zipkin+brave and spring-sleuth is not always clear. AFAIU, spring-sleuth is not required to trace spring-boot apps. It can also easily be done just with zipkin+brave as is. There are some consequences going through sleuth, most notably that it does not have any of the fancier features that brave has been getting. Is my understanding correct ? Maybe this belongs more in the google groups ..

**Comment by adriancole** [comment]
>
> thanks for this, would be helpful. In addition to this, the relation
> between zipkin+brave and spring-sleuth is not always clear. AFAIU,
> spring-sleuth is not required to trace spring-boot apps. It can also easily
> be done just with zipkin+brave as is. There are some consequences going
> through sleuth, most notably that it does not have any of the fancier
> features that brave has been getting. Is my understanding correct ? Maybe
> this belongs more in the google groups ..
>
probably good fodder for google groups, but will take a try at it here.
Indeed some are using brave in spring boot, but such code doesn't get
magical attention of @marcingrzejszczak and others who are maintaining
spring boot tracing via spring-cloud-sleuth.

We don't currently have any integration between brave and
spring-cloud-sleuth mainly as no-one has asked for it. If this was in
place, you could potentially have brave and sleuth instrumentation in the
same app (one being the master), with traces flowing between the two. For
example, we have successfully piloted things like this in Finagle (which
also has its own tracing system). So, if you are looking to mix-match,
raising an issue on sleuth is a good way to start a discussion of that
nature.

Spring-cloud-sleuth and brave are wire-compatible (using B3 headers and
zipkin format), so there's no technical requirement for a homogenous
decision across apps. That said, there may be non-technical reasons to go
one way or another.

cc @devinsba @shakuzen

**Comment by marcingrzejszczak** [comment]
Yeah if more people get interested in it, we could think of writing some sort of a bridge between Brave and Sleuth. As for the features, I'm more than certain that all the shiny features that Brave has and the community likes it, will eventually also end up in Sleuth - don't worry about it @jorgheymans :)

**Comment by carande** [comment]
I'd also be very interested to see a spring-boot example here!

**Comment by adriancole** [comment]
@Sef135 also asked because they can't upgrade to spring boot 2 yet

**Comment by Sef135** [comment]
When I cant't upgrade the srping boot version . there are not Example  of plain spring boot .

**Comment by adriancole** [comment]
please take a look https://github.com/openzipkin/brave-webmvc-example/pull/25 cc @ImFlog
