### ISSUE TITLE
Zipkin brave and Kafka transports using XML

### ISSUE THREAD

**Issue by hayath91** [openzipkin/brave-webmvc-example#19]
I have 3 projects, namely Project A which is the Data layer. Project B which acts as the rest client of Project A. Project C is a web application, having dependency as Project B. Built using Java and Spring mvc. Have configured all 3 projects as given in the example, and giving "zipkin:service" as "app". Built success on Maven and run on Tomcat using Eclipse. When seen from Zipkin UI, when a request is given from Project C, it shows traces coming from three different projects, and not as a single trace, going from Project C to Project A, thru Project B. What am I missing or should I be trying a different instrumentation for a project structure like this. Please help me.

**Comment by adriancole** [comment]
are you using latest brave 4.9.2? there was a bug if you were recording in
v1 format if using prior version

**Comment by hayath91** [comment]
Using brave 4.9.1. Will check and update.

**Comment by hayath91** [comment]
Doesn't work. Recording in v2 format, by the way.

**Comment by adriancole** [comment]
Another way is if you capture /api/v2/trace/your-trace-id

**Comment by hayath91** [comment]
Worked for me. Thanks a lot!

Need high level instructions to do the same using Kafka instead of HttpTracing. Please help.

**Comment by adriancole** [comment]
add this to your pom and replace configuring OkHttpSender with KafkaSender

<dependency>
  <groupId>io.zipkin.reporter2</groupId>
  <artifactId>zipkin-sender-kafka11</artifactId>
  <version>2.1.4</version>
</dependency>

**Comment by hayath91** [comment]
Can we configure KafkaSender using XML itself? If so, please let me know the interceptors needed.

**Comment by adriancole** [comment]
yes, if you look at the xml it is the same as configuring a java type. just
change from OkHttp to Kafka there as if you were doing it in java.

**Comment by hayath91** [comment]
Thanks, Is it possible to change default "zipkin" kafka topic name? If possible how to change?

**Comment by adriancole** [comment]
I don't see a way to do this at the moment in XML as it requires modeling
KafkaSender.newBuilder().topic("zipkin")...build() in XML format. I don't
yet know if we can do this with normal XML or if we need to make a bean
factory...

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-reporter-java/pull/83 will fix this.
