### ISSUE TITLE
Should use "java.lang.String" instead of "String" as type in `constructor-arg` tag of OkHttpSender's factory method

### ISSUE THREAD

**Issue by garymabin** [openzipkin/brave-webmvc-example#20]
https://github.com/openzipkin/brave-webmvc-example/blob/4ea3aed16356234e68f2f1e0c194add8c5b6f3e3/servlet25/src/main/webapp/WEB-INF/spring-webmvc-servlet.xml#L17

README here needs to be fixed as well: https://github.com/openzipkin/brave/tree/master/spring-beans#brave-spring-beans

**Comment by adriancole** [comment]
thanks good catch
