### ISSUE TITLE
Sample code for Spring 2.X is not working since Spring Rest Template is not available in Spring 2.X

### ISSUE THREAD

**Issue by garymabin** [openzipkin/brave-webmvc-example#21]
Spring Rest Template is not available until Spring3. While in the sample code `brave-instrument-spring-web` is dependent on Spring Rest Template, more specifically is `TracingClientHttpRequestIntercepter` depends on `ClientHttpRequestInterceptor`

**Comment by adriancole** [comment]
what's the alternative for less than spring 3? What client should we use?
UrlConnection?

**Comment by garymabin** [comment]
Haven't spent much time on the investigation, it seems Spring rest template is quite independent, so my solution is just copy `spring rest template` from Spring 3+ and makes it a private library. Probably what is needed here is to give some instructions for those who want to trace their Spring 2.X application.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-reporter-java/pull/83 is the first part of getting spring 2.x working

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave-webmvc-example/pull/22 is awaiting a brave release

**Comment by adriancole** [comment]
ok try it out now and re-open if needed!
