### ISSUE TITLE
Help about Spring Boot Option ? it seems does not work

### ISSUE THREAD

**Issue by nicktming** [openzipkin/brave-webmvc-example#27]
when i tried following the instructions in the introducation of webmvc4-boot, Backend and Frontend had different trace_id, by the way the webmvc4 works.

i did as follows:
1. git clone https://github.com/openzipkin/brave-webmvc-example.git
2. cd webmvc4-boot
3. mvn compile exec:java -Dexec.mainClass=brave.webmvc.Backend
4. mvn compile exec:java -Dexec.mainClass=brave.webmvc.Frontend
5. java -jar zipkin.jar
6. curl -s localhost:8081 -H'user-name: JC'

The Result :
brave.webmvc.Frontend : [de8e059e2458c13a/de8e059e2458c13a]
brave.webmvc.Backend : [5762ebf5fd9fcb52/5762ebf5fd9fcb52]

is there anything wrong? Thanks.

**Comment by adriancole** [comment]
sorry this is a configuration bug. this stuff is tricky which is why there's a fair amount of code in spring-cloud-sleuth https://github.com/openzipkin/brave-webmvc-example/pull/28

**Comment by nicktming** [comment]
Thanks.
