### ISSUE TITLE
WebMVC3 configuration not working with spring 5.1.2.RELEASE

### ISSUE THREAD

**Issue by kumar-chandan-kc** [openzipkin/brave-webmvc-example#43]
Hey, I have a project on spring 5.1.2.RELEASE, I did the same configuration as mentioned in WEBMVC3 but it isn't working. To double check I ran WEBMVC3 with zipkin server and it was working fine.

**Comment by kumar-chandan-kc** [comment]
apply plugin: 'java' 
apply plugin: 'war'  
apply plugin: 'eclipse' 
apply plugin: 'eclipse-wtp'

sourceCompatibility = 11
version = '1.0'

task getBuildNumber {
    ext.env = System.getenv()
    ext.buildNumber = env.BUILD_NUMBER?.toInteger()
    File outputFile = file('src/main/webapp/X.version')
    outputFile.write "Build Number: $buildNumber"
}

war {
	archiveName 'X-nc.war'
    destinationDir = file("$buildDir/libs")
	from("${project.rootDir}/src/main/resources") {
      rootSpec.exclude ('**/logback.xml')
      into('WEB-INF/classes')
  	}
  	from("${project.rootDir}/src/main/web"){
    exclude('**/WEB-INF/*')
    }
    rootSpec.rename 'logback-nc.xml', 'logback.xml'
}

repositories {
//   jcenter()
	mavenLocal()
    mavenCentral()
 //   maven { url 'https://repo1.maven.org/maven2' }
    maven { url 'https://repo.gradle.org/gradle/libs' }
 //   maven {	url 'http://54.212.219.76:9989/repository/X-snaphots/master' }
}

configurations.all {
   exclude group: "commons-logging", module: "commons-logging"
}

dependencies {
//    compile group: 'com.X', name: 'X-common-utils', version: '5.0.0-SNAPSHOT'
    compile group: 'commons-collections', name: 'commons-collections', version: '3.2'
    testCompile group: 'junit', name: 'junit', version: '4.+'
    testCompile "org.mockito:mockito-core:3.2.0"
 	compile 'org.springframework:spring-test:5.1.12.RELEASE'	
	compile 'org.apache.servicemix.bundles:org.apache.servicemix.bundles.aopalliance-1.0:1.0.0-rc1'
    compile 'org.springframework:spring-webmvc:5.1.12.RELEASE'
    compile 'org.springframework:spring-beans:5.1.12.RELEASE'
    compile 'org.springframework:spring-core:5.1.12.RELEASE'
    compile 'org.springframework:spring-context:5.1.12.RELEASE'
    compile 'org.springframework:spring-expression:5.1.12.RELEASE'
    compile 'org.springframework:spring-context-support:5.1.12.RELEASE'
    compile 'org.springframework:spring-web:5.1.12.RELEASE'
    compile 'org.springframework:spring-oxm:5.1.12.RELEASE'
    compile 'com.thoughtworks.xstream:xstream:1.4.8'
    compile 'org.slf4j:slf4j-api:1.7.12'
    compile group: 'javax.servlet', name: 'javax.servlet-api', version: '3.0.1'
    compile 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'
    compile 'org.springframework:spring-tx:5.1.12.RELEASE'
    compile 'org.springframework:spring-orm:5.1.12.RELEASE'
    compile 'org.hibernate:hibernate-entitymanager:5.4.2.Final'
    compile 'org.hibernate:hibernate-core:5.4.2.Final'
    compile 'mysql:mysql-connector-java:8.0.16'
    compile 'org.apache.commons:commons-dbcp2:2.1.1'
    compile 'org.apache.commons:commons-pool2:2.4.2'
    compile 'javax.transaction:javax.transaction-api:1.2'
    compile 'org.springframework:spring-aop:5.1.12.RELEASE'
    compile 'org.aspectj:aspectjrt:1.8.7'
    compile 'org.aspectj:aspectjweaver:1.8.7' 
    compile 'com.fasterxml.jackson.core:jackson-databind:2.10.0'
    compile 'com.fasterxml.jackson.core:jackson-core:2.10.0'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.10.0'
    compile 'commons-configuration:commons-configuration:1.10'
    compile 'commons-lang:commons-lang:2.2'
    compile fileTree(dir: 'src/main/webapp/WEB-INF/lib', include: ['*.jar'])
    compile 'org.apache.geronimo.specs:geronimo-servlet_3.0_spec:1.0'
   	compile 'com.hazelcast:hazelcast-all:3.8.4'
   	compile 'org.slf4j:jcl-over-slf4j:1.7.12'
   	compile 'ch.qos.logback:logback-classic:1.1.7'
	compile 'ch.qos.logback:logback-core:1.1.7'
	compile group: 'javax.el', name: 'javax.el-api', version: '3.0.0'
	compile group: 'org.glassfish', name: 'javax.el', version: '3.0.0'
	compile group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    compile group: 'org.hibernate', name: 'hibernate-validator', version: '6.0.16.Final'
    compile group: 'commons-httpclient', name: 'commons-httpclient', version: '3.0'
    compile group: 'org.json', name: 'json', version: '20140107'
    compile group: 'org.reflections', name: 'reflections', version: '0.9.10'
	compile group: 'commons-fileupload', name: 'commons-fileupload', version: '1.4'
	compile group: 'commons-io', name: 'commons-io', version: '2.6'
	compile group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.3.1'
	compile group: 'com.squareup.okhttp', name: 'okhttp', version: '2.7.5'
	compile group: 'io.zipkin.brave', name: 'brave-bom', version: '5.12.3'
	compile group: 'io.zipkin.brave', name: 'brave-instrumentation-spring-webmvc', version: '5.12.6'
	compile group: 'io.zipkin.brave', name: 'brave-instrumentation-httpclient', version: '4.3.1'
	compile group: 'io.zipkin.brave', name: 'brave-spring-beans', version: '5.12.6'
	compile group: 'io.zipkin.brave', name: 'brave', version: '5.12.6'
	compile group: 'io.zipkin.reporter2', name: 'zipkin-reporter-brave', version: '2.15.1'
	compile group: 'io.zipkin.reporter2', name: 'zipkin-sender-okhttp3', version: '2.0.0'

	
	compile group: 'log4j', name: 'log4j', version: '1.2.17'
	compile group: 'io.zipkin.brave', name: 'brave-context-log4j12', version: '5.12.6'
	
	
	
	
	
	
	
	
    
 //   compile group: 'com.googlecode', name: 'json-simple', version: '1.1.1'
	compile 'com.google.code.gson:gson:2.2.4'
	compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.4.1'
	compile group: 'com.sun.xml.bind', name: 'jaxb-core', version: '2.3.0'
	compile group: 'org.jasypt', name: 'jasypt', version: '1.9.0'
	compile 'javax.xml.bind:jaxb-api:2.3.1'
	compile 'javax.activation:activation:1.1.1'
	compile 'org.glassfish.jaxb:jaxb-runtime:2.3.0'
    
}



task copyConfig(type: Copy) {
   from 'build/classes/main'
   into 'src/main/java/config'
}


task commonConfigJar(type: Jar) {
jar.archiveName = "X-nodecontroller-service.1.0.jar"
   from(sourceSets.main.java) {
       include "com/X/**/**/*"
   }
}

sourceSets {
   main {
       java {
           srcDir 'src/main/java'
       }
   }
}

test {
    systemProperties 'property': 'value'
    
    systemProperty "DB_CREDENTIAL_PATH", System.getProperty("DB_CREDENTIAL_PATH")
	 println "system properties of DB_CREDENTIAL_PATH = ${System.properties['DB_CREDENTIAL_PATH']}"
    
}

classes{
	dependsOn getBuildNumber
}

uploadArchives {
    repositories {
       flatDir {
           dirs 'repos'
       }
    }
}

**Comment by kumar-chandan-kc** [comment]
I have a single application context file which is as follows:

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:aop="http://www.springframework.org/schema/aop"
	 xmlns:mvc="http://www.springframework.org/schema/mvc"
	  xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans.xsd
	http://www.springframework.org/schema/tx
	http://www.springframework.org/schema/tx/spring-tx.xsd
	http://www.springframework.org/schema/aop
	http://www.springframework.org/schema/aop/spring-aop.xsd
	http://www.springframework.org/schema/util
	http://www.springframework.org/schema/util/spring-util.xsd	
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context.xsd
   http://www.springframework.org/schema/mvc
http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd">
	<bean id="applicationConfigProp"
		class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name='ignoreResourceNotFound' value='true' />
		<property name="locations">
			<list>
				<value>classpath:config/application-#{ systemProperties['envId'] == null ? 'local' : systemProperties['envId']}.properties</value> 
				<value>${appConfig}</value>
			</list>
		</property>
	</bean>
	
	
	 <bean id="appConfigurationBuilder" class="com.X.cache.model.CacheConfig$Builder">
        
        
        <property name="connectionUrl" value="${app.cache.server.connection.string}"/>
        <property name="name" value="${app.cache.cluster.name}"/>
        <property name="authName" value="${app.cache.group.name}"/>
        <property name="authPassword" value="${app.cache.group.password}"/>
        <property name="cacheType" value="${app.cache.type}"/>
    </bean>
    <bean id="appCacheConfig" factory-bean="appConfigurationBuilder" factory-method="build" />
    
	<bean id="cacheClients" class="com.X.cache.CacheClientFactory" >
	</bean>
	
	<bean id="cacheClientFactory" factory-bean="cacheClients" factory-method="registerCache" >
	 <constructor-arg>
	 	<list>  
			<ref bean="appCacheConfig"/>  
		</list>  
	 </constructor-arg>
	</bean>
	
	<bean id="cacheManager" class="com.X.cacheservice.CacheManager"
		init-method="initialise" destroy-method="shutDown">
		<property name="cacheRegister" ref="cacheClientFactory" />
		
	</bean>
	

	<bean id="messageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="defaultEncoding" value="UTF-8" />
		<property name="basenames">
			<list>
				<value>classpath:/config/resourceBundle/Messages</value>
			</list>
		</property>

	</bean>
	<bean id="localeResolver"
		class="org.springframework.web.servlet.i18n.SessionLocaleResolver">
		<property name="defaultLocale" value="en_US" />
	</bean>
	<bean id="localeChangeInterceptor"
		class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor">
		<property name="paramName" value="language" />
	</bean>
	<bean
		class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping">
		<property name="interceptors">
			<list>
				<ref bean="localeChangeInterceptor" />
			</list>
		</property>
	</bean>
		<bean id="httpClientBuilder" class="brave.httpclient.TracingHttpClientBuilder"
      factory-method="create">
    <constructor-arg ref="httpTracing"/>
  </bean>
  <bean id="httpClient" factory-bean="httpClientBuilder" factory-method="build"/>

  <bean id="restTemplate" class="org.springframework.web.client.RestTemplate">
    <constructor-arg>
      <bean class="org.springframework.http.client.HttpComponentsClientHttpRequestFactory">
        <constructor-arg ref="httpClient"/>
      </bean>
    </constructor-arg>
  </bean>
  

 

    <mvc:interceptors>
    <bean class="brave.spring.webmvc.SpanCustomizingHandlerInterceptor"/>
  </mvc:interceptors> 
   <mvc:annotation-driven/>
	 <bean id="sender" class="zipkin2.reporter.beans.OkHttpSenderFactoryBean">
    <property name="endpoint" value="http://localhost:9411/api/v2/spans"/>
  </bean>
	 
  <bean id="zipkinSpanHandler" class="zipkin2.reporter.beans.AsyncZipkinSpanHandlerFactoryBean">
    <property name="sender" ref="sender"/>
    
    <property name="closeTimeout" value="500"/>
  </bean>
	  <bean id="correlationScopeDecorator" class="brave.spring.beans.CorrelationScopeDecoratorFactoryBean">
    <property name="builder">
      <bean class="brave.context.log4j12.MDCScopeDecorator" factory-method="newBuilder"/>
    </property>
    <property name="configs">
      <list>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.TRACE_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.SPAN_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField" ref="userNameBaggageField"/>
        </bean>
      </list>
    </property>
  </bean>
	  <bean id="userNameBaggageField" class="brave.baggage.BaggageField" factory-method="create">
    <constructor-arg value="userName" />
  </bean>
  <bean id="propagationFactory" class="brave.spring.beans.BaggagePropagationFactoryBean">
    <property name="configs">
      <bean class="brave.spring.beans.SingleBaggageFieldFactoryBean">
        <property name="field" ref="userNameBaggageField" />
        <property name="keyNames" value="user_name" />
      </bean>
    </property>
  </bean>
	  <bean id="tracing" class="brave.spring.beans.TracingFactoryBean">
    <property name="localServiceName" value="nodecontrollergateway"/>
    <property name="propagationFactory" ref="propagationFactory"/>
    <property name="currentTraceContext">
      <bean class="brave.spring.beans.CurrentTraceContextFactoryBean">
        <property name="scopeDecorators" ref="correlationScopeDecorator"/>
      </bean>
    </property>
    <property name="spanHandlers" ref="zipkinSpanHandler"/>
  </bean>
   
  <bean id="spanCustomizer" class="brave.CurrentSpanCustomizer" factory-method="create">
    <constructor-arg index="0" ref="tracing"/>
  </bean>
	  <bean id="httpTracing" class="brave.spring.beans.HttpTracingFactoryBean">
    <property name="tracing" ref="tracing"/>
  </bean>

</beans>

**Comment by kumar-chandan-kc** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:aop="http://www.springframework.org/schema/aop"
	 xmlns:mvc="http://www.springframework.org/schema/mvc"
	  xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans.xsd
	http://www.springframework.org/schema/tx
	http://www.springframework.org/schema/tx/spring-tx.xsd
	http://www.springframework.org/schema/aop
	http://www.springframework.org/schema/aop/spring-aop.xsd
	http://www.springframework.org/schema/util
	http://www.springframework.org/schema/util/spring-util.xsd	
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context.xsd
   http://www.springframework.org/schema/mvc
http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd">
	<bean id="applicationConfigProp"
		class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name='ignoreResourceNotFound' value='true' />
		<property name="locations">
			<list>
				<value>classpath:config/application-#{ systemProperties['envId'] == null ? 'local' : systemProperties['envId']}.properties</value> 
				<value>${appConfig}</value>
			</list>
		</property>
	</bean>
	
	
	 <bean id="appConfigurationBuilder" class="com.azuga.cache.model.CacheConfig$Builder">
        
        
        <property name="connectionUrl" value="${app.cache.server.connection.string}"/>
        <property name="name" value="${app.cache.cluster.name}"/>
        <property name="authName" value="${app.cache.group.name}"/>
        <property name="authPassword" value="${app.cache.group.password}"/>
        <property name="cacheType" value="${app.cache.type}"/>
    </bean>
    <bean id="appCacheConfig" factory-bean="appConfigurationBuilder" factory-method="build" />
    
	<bean id="cacheClients" class="com.azuga.cache.CacheClientFactory" >
	</bean>
	
	<bean id="cacheClientFactory" factory-bean="cacheClients" factory-method="registerCache" >
	 <constructor-arg>
	 	<list>  
			<ref bean="appCacheConfig"/>  
		</list>  
	 </constructor-arg>
	</bean>
	
	<bean id="cacheManager" class="com.azuga.cacheservice.CacheManager"
		init-method="initialise" destroy-method="shutDown">
		<property name="cacheRegister" ref="cacheClientFactory" />
		
	</bean>
	

	<bean id="messageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="defaultEncoding" value="UTF-8" />
		<property name="basenames">
			<list>
				<value>classpath:/config/resourceBundle/Messages</value>
			</list>
		</property>

	</bean>
	<bean id="localeResolver"
		class="org.springframework.web.servlet.i18n.SessionLocaleResolver">
		<property name="defaultLocale" value="en_US" />
	</bean>
	<bean id="localeChangeInterceptor"
		class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor">
		<property name="paramName" value="language" />
	</bean>
	<bean
		class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping">
		<property name="interceptors">
			<list>
				<ref bean="localeChangeInterceptor" />
			</list>
		</property>
	</bean>
		<bean id="httpClientBuilder" class="brave.httpclient.TracingHttpClientBuilder"
      factory-method="create">
    <constructor-arg ref="httpTracing"/>
  </bean>
  <bean id="httpClient" factory-bean="httpClientBuilder" factory-method="build"/>

  <bean id="restTemplate" class="org.springframework.web.client.RestTemplate">
    <constructor-arg>
      <bean class="org.springframework.http.client.HttpComponentsClientHttpRequestFactory">
        <constructor-arg ref="httpClient"/>
      </bean>
    </constructor-arg>
  </bean>
  

 

    <mvc:interceptors>
    <bean class="brave.spring.webmvc.SpanCustomizingHandlerInterceptor"/>
  </mvc:interceptors> 
   <mvc:annotation-driven/>
	 <bean id="sender" class="zipkin2.reporter.beans.OkHttpSenderFactoryBean">
    <property name="endpoint" value="http://localhost:9411/api/v2/spans"/>
  </bean>
	 
  <bean id="zipkinSpanHandler" class="zipkin2.reporter.beans.AsyncZipkinSpanHandlerFactoryBean">
    <property name="sender" ref="sender"/>
    
    <property name="closeTimeout" value="500"/>
  </bean>
	  <bean id="correlationScopeDecorator" class="brave.spring.beans.CorrelationScopeDecoratorFactoryBean">
    <property name="builder">
      <bean class="brave.context.log4j12.MDCScopeDecorator" factory-method="newBuilder"/>
    </property>
    <property name="configs">
      <list>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.TRACE_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.SPAN_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField" ref="userNameBaggageField"/>
        </bean>
      </list>
    </property>
  </bean>
	  <bean id="userNameBaggageField" class="brave.baggage.BaggageField" factory-method="create">
    <constructor-arg value="userName" />
  </bean>
  <bean id="propagationFactory" class="brave.spring.beans.BaggagePropagationFactoryBean">
    <property name="configs">
      <bean class="brave.spring.beans.SingleBaggageFieldFactoryBean">
        <property name="field" ref="userNameBaggageField" />
        <property name="keyNames" value="user_name" />
      </bean>
    </property>
  </bean>
	  <bean id="tracing" class="brave.spring.beans.TracingFactoryBean">
    <property name="localServiceName" value="nodecontrollergateway"/>
    <property name="propagationFactory" ref="propagationFactory"/>
    <property name="currentTraceContext">
      <bean class="brave.spring.beans.CurrentTraceContextFactoryBean">
        <property name="scopeDecorators" ref="correlationScopeDecorator"/>
      </bean>
    </property>
    <property name="spanHandlers" ref="zipkinSpanHandler"/>
  </bean>
   
  <bean id="spanCustomizer" class="brave.CurrentSpanCustomizer" factory-method="create">
    <constructor-arg index="0" ref="tracing"/>
  </bean>
	  <bean id="httpTracing" class="brave.spring.beans.HttpTracingFactoryBean">
    <property name="tracing" ref="tracing"/>
  </bean>

</beans>

**Comment by kumar-chandan-kc** [comment]
_**<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:aop="http://www.springframework.org/schema/aop"
	 xmlns:mvc="http://www.springframework.org/schema/mvc"
	  xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans.xsd
	http://www.springframework.org/schema/tx
	http://www.springframework.org/schema/tx/spring-tx.xsd
	http://www.springframework.org/schema/aop
	http://www.springframework.org/schema/aop/spring-aop.xsd
	http://www.springframework.org/schema/util
	http://www.springframework.org/schema/util/spring-util.xsd	
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context.xsd
   http://www.springframework.org/schema/mvc
http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd">
	<bean id="applicationConfigProp"
		class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name='ignoreResourceNotFound' value='true' />
		<property name="locations">
			<list>
				<value>classpath:config/application-#{ systemProperties['envId'] == null ? 'local' : systemProperties['envId']}.properties</value> 
				<value>${appConfig}</value>
			</list>
		</property>
	</bean>
	
	
	 <bean id="appConfigurationBuilder" class="com.azuga.cache.model.CacheConfig$Builder">
        
        
        <property name="connectionUrl" value="${app.cache.server.connection.string}"/>
        <property name="name" value="${app.cache.cluster.name}"/>
        <property name="authName" value="${app.cache.group.name}"/>
        <property name="authPassword" value="${app.cache.group.password}"/>
        <property name="cacheType" value="${app.cache.type}"/>
    </bean>
    <bean id="appCacheConfig" factory-bean="appConfigurationBuilder" factory-method="build" />
    
	<bean id="cacheClients" class="com.azuga.cache.CacheClientFactory" >
	</bean>
	
	<bean id="cacheClientFactory" factory-bean="cacheClients" factory-method="registerCache" >
	 <constructor-arg>
	 	<list>  
			<ref bean="appCacheConfig"/>  
		</list>  
	 </constructor-arg>
	</bean>
	
	<bean id="cacheManager" class="com.azuga.cacheservice.CacheManager"
		init-method="initialise" destroy-method="shutDown">
		<property name="cacheRegister" ref="cacheClientFactory" />
		
	</bean>
	

	<bean id="messageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="defaultEncoding" value="UTF-8" />
		<property name="basenames">
			<list>
				<value>classpath:/config/resourceBundle/Messages</value>
			</list>
		</property>

	</bean>
	<bean id="localeResolver"
		class="org.springframework.web.servlet.i18n.SessionLocaleResolver">
		<property name="defaultLocale" value="en_US" />
	</bean>
	<bean id="localeChangeInterceptor"
		class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor">
		<property name="paramName" value="language" />
	</bean>
	<bean
		class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping">
		<property name="interceptors">
			<list>
				<ref bean="localeChangeInterceptor" />
			</list>
		</property>
	</bean>
		<bean id="httpClientBuilder" class="brave.httpclient.TracingHttpClientBuilder"
      factory-method="create">
    <constructor-arg ref="httpTracing"/>
  </bean>
  <bean id="httpClient" factory-bean="httpClientBuilder" factory-method="build"/>

  <bean id="restTemplate" class="org.springframework.web.client.RestTemplate">
    <constructor-arg>
      <bean class="org.springframework.http.client.HttpComponentsClientHttpRequestFactory">
        <constructor-arg ref="httpClient"/>
      </bean>
    </constructor-arg>
  </bean>
  

 

    <mvc:interceptors>
    <bean class="brave.spring.webmvc.SpanCustomizingHandlerInterceptor"/>
  </mvc:interceptors> 
   <mvc:annotation-driven/>
	 <bean id="sender" class="zipkin2.reporter.beans.OkHttpSenderFactoryBean">
    <property name="endpoint" value="http://localhost:9411/api/v2/spans"/>
  </bean>
	 
  <bean id="zipkinSpanHandler" class="zipkin2.reporter.beans.AsyncZipkinSpanHandlerFactoryBean">
    <property name="sender" ref="sender"/>
    
    <property name="closeTimeout" value="500"/>
  </bean>
	  <bean id="correlationScopeDecorator" class="brave.spring.beans.CorrelationScopeDecoratorFactoryBean">
    <property name="builder">
      <bean class="brave.context.log4j12.MDCScopeDecorator" factory-method="newBuilder"/>
    </property>
    <property name="configs">
      <list>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.TRACE_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.SPAN_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField" ref="userNameBaggageField"/>
        </bean>
      </list>
    </property>
  </bean>
	  <bean id="userNameBaggageField" class="brave.baggage.BaggageField" factory-method="create">
    <constructor-arg value="userName" />
  </bean>
  <bean id="propagationFactory" class="brave.spring.beans.BaggagePropagationFactoryBean">
    <property name="configs">
      <bean class="brave.spring.beans.SingleBaggageFieldFactoryBean">
        <property name="field" ref="userNameBaggageField" />
        <property name="keyNames" value="user_name" />
      </bean>
    </property>
  </bean>
	  <bean id="tracing" class="brave.spring.beans.TracingFactoryBean">
    <property name="localServiceName" value="nodecontrollergateway"/>
    <property name="propagationFactory" ref="propagationFactory"/>
    <property name="currentTraceContext">
      <bean class="brave.spring.beans.CurrentTraceContextFactoryBean">
        <property name="scopeDecorators" ref="correlationScopeDecorator"/>
      </bean>
    </property>
    <property name="spanHandlers" ref="zipkinSpanHandler"/>
  </bean>
   
  <bean id="spanCustomizer" class="brave.CurrentSpanCustomizer" factory-method="create">
    <constructor-arg index="0" ref="tracing"/>
  </bean>
	  <bean id="httpTracing" class="brave.spring.beans.HttpTracingFactoryBean">
    <property name="tracing" ref="tracing"/>
  </bean>

</beans>**_

**Comment by kumar-chandan-kc** [comment]
<bean id="appConfigurationBuilder" class="com.X.cache.model.CacheConfig$Builder">
        
        
        <property name="connectionUrl" value="${app.cache.server.connection.string}"/>
        <property name="name" value="${app.cache.cluster.name}"/>
        <property name="authName" value="${app.cache.group.name}"/>
        <property name="authPassword" value="${app.cache.group.password}"/>
        <property name="cacheType" value="${app.cache.type}"/>
    </bean>
    <bean id="appCacheConfig" factory-bean="appConfigurationBuilder" factory-method="build" />
    
	<bean id="cacheClients" class="com.X.cache.CacheClientFactory" >
	</bean>
	
	<bean id="cacheClientFactory" factory-bean="cacheClients" factory-method="registerCache" >
	 <constructor-arg>
	 	<list>  
			<ref bean="appCacheConfig"/>  
		</list>  
	 </constructor-arg>
	</bean>
	
	<bean id="cacheManager" class="com.X.cacheservice.CacheManager"
		init-method="initialise" destroy-method="shutDown">
		<property name="cacheRegister" ref="cacheClientFactory" />
		
	</bean>
	

	<bean id="messageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="defaultEncoding" value="UTF-8" />
		<property name="basenames">
			<list>
				<value>classpath:/config/resourceBundle/Messages</value>
			</list>
		</property>

	</bean>
	<bean id="localeResolver"
		class="org.springframework.web.servlet.i18n.SessionLocaleResolver">
		<property name="defaultLocale" value="en_US" />
	</bean>
	<bean id="localeChangeInterceptor"
		class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor">
		<property name="paramName" value="language" />
	</bean>
	<bean
		class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping">
		<property name="interceptors">
			<list>
				<ref bean="localeChangeInterceptor" />
			</list>
		</property>
	</bean>
		<bean id="httpClientBuilder" class="brave.httpclient.TracingHttpClientBuilder"
      factory-method="create">
    <constructor-arg ref="httpTracing"/>
  </bean>
  <bean id="httpClient" factory-bean="httpClientBuilder" factory-method="build"/>

  <bean id="restTemplate" class="org.springframework.web.client.RestTemplate">
    <constructor-arg>
      <bean class="org.springframework.http.client.HttpComponentsClientHttpRequestFactory">
        <constructor-arg ref="httpClient"/>
      </bean>
    </constructor-arg>
  </bean>
  

 

    <mvc:interceptors>
    <bean class="brave.spring.webmvc.SpanCustomizingHandlerInterceptor"/>
  </mvc:interceptors> 
   <mvc:annotation-driven/>
	 <bean id="sender" class="zipkin2.reporter.beans.OkHttpSenderFactoryBean">
    <property name="endpoint" value="http://localhost:9411/api/v2/spans"/>
  </bean>
	 
  <bean id="zipkinSpanHandler" class="zipkin2.reporter.beans.AsyncZipkinSpanHandlerFactoryBean">
    <property name="sender" ref="sender"/>
    
    <property name="closeTimeout" value="500"/>
  </bean>
	  <bean id="correlationScopeDecorator" class="brave.spring.beans.CorrelationScopeDecoratorFactoryBean">
    <property name="builder">
      <bean class="brave.context.log4j12.MDCScopeDecorator" factory-method="newBuilder"/>
    </property>
    <property name="configs">
      <list>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.TRACE_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField">
            <util:constant static-field="brave.baggage.BaggageFields.SPAN_ID"/>
          </property>
        </bean>
        <bean class="brave.spring.beans.SingleCorrelationFieldFactoryBean">
          <property name="baggageField" ref="userNameBaggageField"/>
        </bean>
      </list>
    </property>
  </bean>
	  <bean id="userNameBaggageField" class="brave.baggage.BaggageField" factory-method="create">
    <constructor-arg value="userName" />
  </bean>
  <bean id="propagationFactory" class="brave.spring.beans.BaggagePropagationFactoryBean">
    <property name="configs">
      <bean class="brave.spring.beans.SingleBaggageFieldFactoryBean">
        <property name="field" ref="userNameBaggageField" />
        <property name="keyNames" value="user_name" />
      </bean>
    </property>
  </bean>
	  <bean id="tracing" class="brave.spring.beans.TracingFactoryBean">
    <property name="localServiceName" value="nodecontrollergateway"/>
    <property name="propagationFactory" ref="propagationFactory"/>
    <property name="currentTraceContext">
      <bean class="brave.spring.beans.CurrentTraceContextFactoryBean">
        <property name="scopeDecorators" ref="correlationScopeDecorator"/>
      </bean>
    </property>
    <property name="spanHandlers" ref="zipkinSpanHandler"/>
  </bean>
   
  <bean id="spanCustomizer" class="brave.CurrentSpanCustomizer" factory-method="create">
    <constructor-arg index="0" ref="tracing"/>
  </bean>
	  <bean id="httpTracing" class="brave.spring.beans.HttpTracingFactoryBean">
    <property name="tracing" ref="tracing"/>
  </bean>

</beans>

**Comment by adriancole** [comment]
so you are saying that you only change the spring version in the webmvc3 project, and it doesn't operate. is that true?

**Comment by kumar-chandan-kc** [comment]
Yes True.

**Comment by adriancole** [comment]
the webmvc3 project is configured with servlet 2.5 which is conflicting with what spring 5 wants. You can use a different base project or change the servlet/jetty stuff accordingly. In any case XML works with any version of spring https://github.com/openzipkin/brave/tree/master/spring-beans

```
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
	at org.springframework.web.servlet.FrameworkServlet.publishRequestHandledEvent(FrameworkServlet.java:1138)
````
